# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dafcli < Formula
  desc "CLI for querying Datafordeler (Danish grunddata) via GraphQL — MAT, BBR, DAR, DAGI"
  homepage "https://github.com/kaspermunck/dafcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/dafcli/releases/download/v0.1.0/dafcli_darwin_amd64.tar.gz"
      sha256 "f891183d7c768b1007616d5a2fcf33d35582dd7646b4da17d664d32beb809fda"

      define_method(:install) do
        bin.install "dafcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/dafcli/releases/download/v0.1.0/dafcli_darwin_arm64.tar.gz"
      sha256 "e2508df418ac58e624818ff3c022d8b7e29a095f71942b81450283537d392f3c"

      define_method(:install) do
        bin.install "dafcli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/dafcli/releases/download/v0.1.0/dafcli_linux_amd64.tar.gz"
      sha256 "20b8b2f1eea55b5b389228c132d43cfa654e18efe2cc7f3641a1f920a20fecab"
      define_method(:install) do
        bin.install "dafcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/dafcli/releases/download/v0.1.0/dafcli_linux_arm64.tar.gz"
      sha256 "f10aef10ab3d5d28a284ec5caff2aac8c60905e08399f817a63c60514644a48b"
      define_method(:install) do
        bin.install "dafcli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/daf
    EOS
  end

  test do
    system "#{bin}/dafcli", "--help"
  end
end
