# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstcli < Formula
  desc "CLI for querying Danmarks Statistik (DST) data"
  homepage "https://github.com/kaspermunck/dstcli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/dstcli/releases/download/v0.2.0/dstcli_darwin_amd64.tar.gz"
      sha256 "9e5314a3191a0f106a65018244f8e8dd91f8b9b4a6af029bf9a167c77d324daa"

      define_method(:install) do
        bin.install "dstcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/dstcli/releases/download/v0.2.0/dstcli_darwin_arm64.tar.gz"
      sha256 "81a6d5632d2987b684e8bd6828d4823de5361471b95b7f687cecc84637d44a4d"

      define_method(:install) do
        bin.install "dstcli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/dstcli/releases/download/v0.2.0/dstcli_linux_amd64.tar.gz"
      sha256 "bc5636be43fe2108788d2f0b74ce2bc020bc3fa75ec7e844ed6fd7fd10206bae"
      define_method(:install) do
        bin.install "dstcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/dstcli/releases/download/v0.2.0/dstcli_linux_arm64.tar.gz"
      sha256 "72360f3d61e2c4183246d080cdea5cd819ee4038b45d30aab9bd8231d43317fd"
      define_method(:install) do
        bin.install "dstcli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/dst
    EOS
  end

  test do
    system "#{bin}/dstcli", "--help"
  end
end
