# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftcli < Formula
  desc "CLI for querying Folketingets Open Data (oda.ft.dk) — cases, MPs, votes, documents"
  homepage "https://github.com/kaspermunck/ftcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/ftcli/releases/download/v0.1.0/ftcli_darwin_amd64.tar.gz"
      sha256 "0424a05f249e9089097567c767392c02f7c8b4c1695473cb1672f1534f21a848"

      define_method(:install) do
        bin.install "ftcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/ftcli/releases/download/v0.1.0/ftcli_darwin_arm64.tar.gz"
      sha256 "377595efe88c28d957442c88b57ea3165f88bdfc88e9004d113eff7fbfd83886"

      define_method(:install) do
        bin.install "ftcli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/ftcli/releases/download/v0.1.0/ftcli_linux_amd64.tar.gz"
      sha256 "44aef21b8afc6e4d009ae1184cffa537fdadb6b199d3bdf813027c395e33f716"
      define_method(:install) do
        bin.install "ftcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/ftcli/releases/download/v0.1.0/ftcli_linux_arm64.tar.gz"
      sha256 "618b30c73008c72e34908e04904d07adae480a413dcce4553429afae340bddb7"
      define_method(:install) do
        bin.install "ftcli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/ft
    EOS
  end

  test do
    system "#{bin}/ftcli", "--help"
  end
end
