# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retscli < Formula
  desc "CLI for querying Danish legal information (love, bekendtgørelser) via Retsinformation API"
  homepage "https://github.com/kaspermunck/retscli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/retscli/releases/download/v0.1.0/retscli_darwin_amd64.tar.gz"
      sha256 "765f71b7179a4bafa6c87edcb44bb8f4350e4f55c17540ef42efe6a180483c68"

      define_method(:install) do
        bin.install "retscli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/retscli/releases/download/v0.1.0/retscli_darwin_arm64.tar.gz"
      sha256 "0c2973bdedc827b38b91a324a5c0049dd5164180d5b8b7e4733dc7b3fd5f6365"

      define_method(:install) do
        bin.install "retscli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/retscli/releases/download/v0.1.0/retscli_linux_amd64.tar.gz"
      sha256 "cc9bf33c1adb2315effd4c89edf41b1e8fc813b442d9558c34b67ba64d17c03d"
      define_method(:install) do
        bin.install "retscli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/retscli/releases/download/v0.1.0/retscli_linux_arm64.tar.gz"
      sha256 "45e48963decf3fbc070e7909f965609eac25dbf908eae1847c345a487d591057"
      define_method(:install) do
        bin.install "retscli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/rets
    EOS
  end

  test do
    system "#{bin}/retscli", "--help"
  end
end
