# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Virkcli < Formula
  desc "CLI for querying Danish company data via the official VIRK / CVR API"
  homepage "https://github.com/kaspermunck/virkcli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.2.0/virkcli_darwin_amd64.tar.gz"
      sha256 "dc1842a58d53bf20edf47a5c2a954df2b4c7293d57de8a483255ddc67c4d3008"

      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.2.0/virkcli_darwin_arm64.tar.gz"
      sha256 "923b4fe6bb50c078c68d3e5346cbc1e1ea8a1d880bd751bac659f9acb8bfafb1"

      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.2.0/virkcli_linux_amd64.tar.gz"
      sha256 "7b03b16c0a0ea834ca08a7bbb83668817a0f228ed69b0d4254620c11735ae0f1"
      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.2.0/virkcli_linux_arm64.tar.gz"
      sha256 "b2eff8243c9077fe9edd92fa25f1cef303b54cae5fe3d76267db6914a8e33e88"
      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/virk
    EOS
  end

  test do
    system "#{bin}/virkcli", "--help"
  end
end
