# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Virkcli < Formula
  desc "CLI for querying Danish company data via the official VIRK / CVR API"
  homepage "https://github.com/kaspermunck/virkcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.1.0/virkcli_darwin_amd64.tar.gz"
      sha256 "d91bb81c0a3d661be6dd2b1da6a5bf33a065231db31719e1ed0051877a8884c7"

      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.1.0/virkcli_darwin_arm64.tar.gz"
      sha256 "e52fc357d1c34f515407d00229e3aa94de6cf49e3fd2d9864e2b063579fe6d5e"

      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.1.0/virkcli_linux_amd64.tar.gz"
      sha256 "31482b92f5609ecfdb71d475690ee928c3eaeea8786a82a97733c50b1fd14553"
      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspermunck/virkcli/releases/download/v0.1.0/virkcli_linux_arm64.tar.gz"
      sha256 "b141321b62692e3374854314d5fff7fcaf0295009932f3fbbfe78b1082673e25"
      define_method(:install) do
        bin.install "virkcli"
        pkgshare.install "skill"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the Claude Code skill, run once:
        mkdir -p ~/.claude/skills && ln -sfn #{opt_pkgshare}/skill ~/.claude/skills/virk
    EOS
  end

  test do
    system "#{bin}/virkcli", "--help"
  end
end
